#!/bin/sh
PS1='\e[1;37m\u@\h\e[0m:\e[1;36m\w\e[0m\$ \e[?16;0;250c'
export PS1='\e[1;37m\u@\h\e[0m:\e[1;36m\w\e[0m\$ \e[?16;0;250c'
loadfont < /etc/OneCore/font
printf "$PS1"
mount proc
grep -qw multivt /proc/cmdline && sed -i s/^#tty/tty/ /etc/inittab
if ! grep -qw noembed /proc/cmdline; then

  inodes=`grep MemFree /proc/meminfo | awk '{printf("%d\n", $2/3)}'`

  mount / -o remount,size=90%,nr_inodes=$inodes
  umount proc
  exec /sbin/init
fi
umount proc
if mount -t tmpfs -o size=90% tmpfs /mnt; then
  if tar -C / --exclude=mnt -cf - . | tar -C /mnt/ -xf - ; then
    mkdir /mnt/mnt
    exec /sbin/switch_root mnt /sbin/init
  fi
fi
exec /sbin/init
